page_view
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=page_view&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1

Entrance
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=entrance&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_banner
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_banner&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_accepted_all
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_accepted_all&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_rejected_all
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_rejected_all&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_selection
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_selection&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_link_cookies
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.cookieless}}&cid={{JS.getSessionId}}&en=consents_link_cookies&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_settings
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_settings&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
consents_changed
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=consents_changed&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1
Purchase
//region1.analytics.google.com/g/collect?v=2&tid={{GA4.ID.COOKIELESS}}&cid={{JS.getSessionId}}&en=purchase&dl={{Page URL}}&dr={{Referrer}}&dt={{Page Path}}&gcs=G111&ep.page_type={{DLV.pageType}}&ep.content_group={{DLV.pageType}}&ep.consents=fun~{{Consent source - functional_storage}}~~ana~{{Consent source - analytics_storage}}~~ads~{{Consent source - ad_storage}}~~per~{{Consent source - personalization_storage}}&ep.user_agent={{GJS.userAgent}}&_dbg=1&ep.purchase_id={{DLV.ecommerce.purchase.actionField.id}}&ep.purchase_revenue={{DLV.ecommerce.purchase.actionField.revenue}}
